experiment_name: alignflow

seed: 42
epochs: 5
noise_aug: False
noise_aug_level: 0.1
normalization: standardize    # min_max, standardize or none
shuffle: 1
condition: none
ml_weight: 1

is_training: True
batch_size: 1
gpu_ids: 0
initializer: normal
kernel_size_d: 4
norm_type: instance
num_scales: 3
num_blocks: 4
num_channels: 16
num_channels_d: 64
num_channels_g: 64
num_workers: 16
phase: train
use_dropout: False
lambda_src: 10
lambda_tgt: 10
lambda_id: 0.5
lambda_l1: 100
lambda_mle: 1.0
beta_1: 0.5
beta_2: 0.999
lr: 2e-4
rnvp_beta_1: 0.5
rnvp_beta_2: 0.999
rnvp_lr: 2e-4
weight_norm_l2: 5e-5
lr_policy: linear
lr_step_epochs: 100
lr_warmup_epochs: 100
lr_decay_epochs: 100
use_mixer: True
clamp_jacobian: True
clip_gradient: True
jc_lambda_min: 1.0
jc_lambda_max: 20.0


data:
  data_set_name: real_sim     # real_sim, sim or mnist_usps
  data_dir_a: test_dir_a
  data_dir_b: test_dir_b
  used_channels: 16          # int as index of list [700, 855, 10] or list of int as indices, e.g. [0, 3, 6, 15]
  log: False                 # indicate if data have been taken logarithmic
