experiment_name: unit

epochs: 400
seed: 42
num_workers: 16
shuffle: 1
spectral_consistency: 0
sc_weight: 0.1

# optimization options

batch_size: 3                 # batch size
weight_decay: 0.0001           # weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 10000             # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate
gan_w: 1                      # weight of adversarial loss
recon_x_w: 10                 # weight of image reconstruction loss
recon_h_w: 0                  # weight of hidden reconstruction loss
recon_kl_w: 0.05              # weight of KL loss for reconstruction
recon_x_cyc_w: 10             # weight of cycle consistency loss
recon_kl_cyc_w: 0.05          # weight of KL loss for cycle consistency
vgg_w: 0                      # weight of domain-invariant perceptual loss
recon_criterion: mse
normalization: standardize

# model options
gen:
  dim: 64                     # number of filters in the bottommost layer
  activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
  n_downsample: 2             # number of downsampling layers in content encoder
  n_res: 4                    # number of residual blocks in content encoder/decoder
  pad_type: reflect           # padding type [zero/reflect]
  reduce_dim: False
dis:
  dim: 64                     # number of filters in the bottommost layer
  normalization: none                  # normalization layer [none/bn/in/ln]
  activation: lrelu                # activation function [relu/lrelu/prelu/selu/tanh]
  n_layer: 4                  # number of layers in D
  gan_type: lsgan             # GAN loss [lsgan/nsgan]
  num_scales: 3               # number of scales
  padding_type: reflect           # padding type [zero/reflect]
  dropout: False
  dropout_p: 0.2

# data options
data:
  data_set_name: sim     # real_sim, sim or mnist_usps
  data_dir_a: test_dir_a
  data_dir_b: test_dir_b
  used_channels: 16          # int as index of list [700, 855, 10] or list of int as indices, e.g. [0, 3, 6, 15]
  log: True                 # indicate if data have been taken logarithmic
